"""add created_at column to gif table

Revision ID: 885987996e2f
Revises: 4a2b3cb0434f
Create Date: 2026-09-22 16:56:06.221413

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "885987996e2f"
down_revision: str | Sequence[str] | None = "4a2b3cb0434f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        "images",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("images", "created_at")
    # ### end Alembic commands ###
